### ISSUE TITLE
passing "ies" to natural::stem::get panics

### ISSUE THREAD

**Issue by mt-caret** [christophertrml/rs-natural#17]
I get the message:

```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 18446744073709551615', /c
heckout/src/libcore/slice/mod.rs:2041:10
```

The value seems to indicate an unsigned value dropping below zero.

**Comment by tsturzl** [comment]
There are a few edge cases in the stemmer. I'd like to implement a few other stemmers, but for now I'm just going to try to manage these edge cases. I'll patch this hopefully for the next release.

**Comment by tsturzl** [comment]
I did some passes on refactoring and decided that the stemmer module is very old and not very idiomatic rust. The effort to refactor and improve is high, and implementing my own stemmer seems like reinventing the wheel when there are some great crates out there for this, and I didn't want to redistribute another crate within this one. My current solution to this problem is removing the stemming functionality from this crate entirely and let the user decide which stemmer crate to use, for things like TF-IDF and the classifier I'm using rust-stemmers crate to handle stemming those.
