### ISSUE TITLE
Allow contributors to help maintain

### ISSUE THREAD

**Issue by tsturzl** [christophertrml/rs-natural#18]
Hey @christophertrml ,

I've contributed a few times to the project, and I'd really like to continue to do so. I don't see a ton of options for NLP in Rust. I'd really like to make the library more uniform, and overall more flexible. Currently the tf-idf works but isn't easy to use in a meaningful way. The Naive-Bayes classifier has been in need of some work for a while now, and a logistic regression classifier has been a near-sighted goal since I first learned of the project. I could help handle issues and PRs, as well as expanding the feature set, and improving already existing features of the project if you give me permissions for the repository.

Let me know what you think,

Travis Sturzl

**Comment by tsturzl** [comment]
Some things I'd like to do:

 1. close out all the standing PRs and issues.
 1. Supporting a variety of edgecases for stemming
 1. Support Serde as an optional crate feature for most of the features(classifier, soundex, and tf-idf)
 1. Tackle the near-sighted goals
 1. Add support for basic topic modeling
 1. Supporting parallel operations as an optional crate feature
 1. Start porting features from python's NLTK

**Comment by a2xchip** [comment]
@tsturzl Ability to save tfidf and classifier out of the box would be good to have too))

**Comment by christophertrml** [comment]
Thanks for bumping this @a2xchip , there were a couple of days a couple weeks ago where my e-mail was lost and I think this original PR was one of those that got lost.

Unfortunately my interests and responsibilities have shifted such that this project isn't a priority for me, but I would love if you would basically take it over since I agree that there's a large gap in NLP in Rust and I started this project precisely because I do believe Rust is an excellent bed for ML in the future.

Travis, I'd be happy to make you a contributor to the project and allow you basically free reign over its vision.

**Comment by tsturzl** [comment]
@a2xchip serde support would effectively give a means to serialize and deserialize tf-idf and classifiers in many different formats. I think this would suffice for your needs. This will probably be the first thing I implement. If you're not familiar with serde I definitely recommend you take a look, very useful crate.

**Comment by tsturzl** [comment]
@christophertrml Thanks Christopher. I'll probably start slow at first, but this will be a perfect place to implement a lot of the things I use in my various side projects in a manner that's useful to others.

**Comment by a2xchip** [comment]
@tsturzl Sure, i know `serde` and use it myself)))
